### ISSUE TITLE
Improve docs or can docs be found elsewhere?

### ISSUE THREAD

**Issue by ckormanyos** [modm-io/avr-libstdcpp#10]
This is another question, with no expectation on change, regarding the cool STL port.

When I look at the markdown for this repository, it is very clear what it is.

I would, however, really like to see some more details in the docs in the markdown area.

Simply answering some of the queries/issues listed below would have been enough for me to really get a better idea of what's going on in this work.
* What is the original source of this STL?
* Does it originate from something like an `arm-none-eabi`? Was anything special needed with compiler switches or needed in places like `<config/bits>` area(s)?
* Could you provide more details regarding how the STL port evolved into this state?
* What simplifications were undertaken for IO-streaming (such as primitive char-exchange via UART?)?
* How do you use it? Sure, I see that there is is an example, but how do you add the `whatever/include` path? That kind of stuff would help right up front on the markdown.

I would also recomment, although this is not necessary, getting a CI running. You could put at least one single CI job into this thing that includes your ARV image together with this repo cloned into the CI job-space in order to compile a few things with `<array>` and `<algorithm>`. Compilation (not running/simulating) it would bve a good enough start...

I can/could help with any/all of these matters if you like or if there is any interest in this.

**Comment by ckormanyos** [comment]
> I can/could help with any/all of these matters if you like or if there is any interest in this.

I will probably, at some point in time, take a crack at these items in my own fork. So I am definitely interested in such improvement(s)...

**Comment by chris-durand** [comment]
Hi @ckormanyos,

I am glad you find this work useful. I actually had planned to add more documentation but never got to it. My original motivation for this port was to be able to use things type traits or `std::array` within the modm codebase. Previously we couldn't rely on the standard library at all within modm because our code has to run on AVR. We had a lot of subpar C++98 custom implementations of standard library facilities. Since I haven't used any AVR processor for at least 5 years and have been quite busy with work I never came back to it.

To create this I basically took libstdc++ from the arm gcc source and stripped anything that either needs high level OS support to work or is not supported AVR. Also some adjustments had to be made that the math functions work with avr-libc. Sadly I don't remember all the details anymore.

> I would also recomment, although this is not necessary, getting a CI running.

We indirectly have a CI pipeline in the modm project, we even run some [on-target tests](https://github.com/modm-io/modm/tree/develop/test/stdc%2B%2B) as part of the quarterly release. This was never intended to be its own project and targeted at modm only.

Unfortunately I don't have time right now to continue work on this port and make it more useful to others. We are happy to incorporate any improvements from your fork.

**Comment by ckormanyos** [comment]
Hi @chris-durand thanks for your reply.

> original motivation for this port was to be able to use things type traits or `std::array`

Nod. I have/had very similar uses in my book, mostly including program methods/classes/structures from `<algorithm>`, `<array>`, `<type_traits>`, `<chrono>`, and a few other of the more, let's say, lightweight STL elements.

> To create this I basically took libstdc++ from the arm gcc source and stripped anything that either needs high level OS support to work or is not supported AVR. Also some adjustments had to be made that the math functions work with avr-libc. Sadly I don't remember all the details anymore.

Understood.

>  any improvements from your fork.

I will try and reverse engineer a bit. i can trace back a few things regarding origin, purpose, re-targeting, etc. I will take a crack at some rudimentary documaentation based on what is obvious from reverse-engineering the port, and leaving undocumented what is unclear.

I think it would be nice to have at least one simple CI job running, using this STL port and compiling an example (such as your own using vector) and your AVR GCC on Ubuntu. I am happy to set up such a tiny CI job at some time in a branch and present it to you.

Allow me to take a few steps toward these goals and report later...

Thank you for responding with such clarity.

Cc: @salkinium

**Comment by salkinium** [comment]
Great, thanks for the help! For the CI take a look at [how modm does it](https://github.com/modm-io/modm/blob/develop/.github/workflows/linux.yml#L173), as we have our own [Docker container with an up-to-date avr-gcc v11.2](https://github.com/modm-ext/docker-modm-build).

**Comment by ckormanyos** [comment]
> For the CI take a look at how modm does it, as we have our own Docker ...

Awesomeness! I am aware of the image. I will attempt to comply. Thx.

**Comment by rleh** [comment]
> as we have our own [Docker container with an up-to-date avr-gcc v11.2](https://github.com/modm-ext/docker-modm-build).

If you prefer to install avr-gcc 11.2.0 locally on your (Linux) system, we got you covered as well: https://github.com/modm-io/avr-gcc (same build as installed in the docker container).

**Comment by rleh** [comment]
> I think it would be nice to have at least one simple CI job running, using this STL port and compiling an example (such as your own using vector) and your AVR GCC on Ubuntu.

Done: #12

**Comment by ckormanyos** [comment]
>>  simple CI job running, using this STL port and compiling

> Done #12 

That looks very nice!

**Comment by ckormanyos** [comment]
Notes to self.

- Target application domain (AVR modern C++)
- Origin of work.
- Main changes or types of changes undertaken to adapt for target.
- Limitations: Describe limitations related to 16-bit `ptrdiff_t`, `size_t`, `signed` and `unsigned` versions of `int`?
- Limitations: Describe what happens if `int` is actually 8-bits wide in AVR C/C++-Compiler?
- Limitations: AVR C/C++ compiler will put most `std::array`s (those out-of-function-scope) within RAM. Warn about this.
- Another phenomenon has been discovered. This STL can not be used with `avr-g++` V5.x because that compiler lacks some intrinsics used. This is fine, but the compiler version range (insofar as known) should be delimited.

Cc: @chris-durand and @salkinium and @rleh

**Comment by ckormanyos** [comment]
More notes

- Special use needed for `<chrono>`
- Emphasize the importance of using specialized allocators with STL containers
- Example of custom allocator if needed (or wanted). Could be very cool to offload STL-vector to an external SRAM chip, for instance via use of allocator.
- More notes to come...

**Comment by ckormanyos** [comment]
First very rudimentary [draft of a few thoughts](https://github.com/ckormanyos/avr-libstdcpp/blob/improve_docs_markdown/README.md).

Cc: @salkinium and @chris-durand and @rleh

**Comment by ckormanyos** [comment]
Draft is integrated in main.
