### ISSUE TITLE
ICE when using std::accumulate with AVR-GCC 12.1.0

### ISSUE THREAD

**Issue by asesidaa** [modm-io/avr-libstdcpp#21]
Hi, I am using AVR-GCC 12.1.0 from https://blog.zakkemble.net/avr-gcc-builds/

When I tried to compile the following test code for my arduino uno, an ICE occurred,

The code is 
```c++
#include <Arduino.h>
#include <array>
#include <numeric>

std::array<int, 3> array {1,2,3};

void setup() {
    Serial.begin(115200);
    Serial.println("Hello world");
}

void loop() {
    auto sum = std::accumulate(array.cbegin(), array.cend(), 0);
    Serial.print("Number is ");
    Serial.println(sum);
    delay(1000);
}
```

The error I encountered is
```
Compiling .pio\build\uno\src\main.cpp.o
Linking .pio\build\uno\firmware.elf
during RTL pass: combine
C:\Users\10614\.platformio\packages\framework-arduino-avr\cores\arduino\main.cpp: In function 'main':
C:\Users\10614\.platformio\packages\framework-arduino-avr\cores\arduino\main.cpp:51:1: internal compiler error: in add_clobbers, at config/avr/avr-dimode.md:2705
   51 | }
      | ^
libbacktrace could not find executable to open
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <https://gcc.gnu.org/bugs/> for instructions.
lto-wrapper.exe: fatal error: avr-g++ returned 1 exit status
compilation terminated.
c:/users/10614/.platformio/packages/toolchain-atmelavr/bin/../lib/gcc/avr/12.1.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\uno\firmware.elf] Error 1
```

This error does not occur when using AVR-GCC 11.1.0 (from the same site). I wonder is this caused by this lib or is this a regression bug in GCC or maybe I am doing something wrong?

Thank you

**Comment by asesidaa** [comment]
> Thanks for your report @asesidaa.
> 
> I will try to reproduce the situation using that compiler.
> 
> You are using the STL in this repo correct?

Yes, I am using the STL in this repo (latest version)

**Comment by ckormanyos** [comment]
Hi @asesidaa I was not at the first pass able to reproduce this error nor any similar error behavior.

I ran a whole bunch of tests using my own bare-metal (non-Arduino) environment with Zak's new compiler and also with the `avr-libstdcpp` repo. I used numerous STL headers such as `<array>`, `<algorithm>´, `<numeric>` and more.

> wonder is this caused by this lib or is this a regression bug in GCC or maybe I am doing something wrong?

This is exactly what I was wondering. As a next step we should find out if there is something conflicting the new compiler in your environment.

- I noticed you seem to be using link-time-optimization (probably via `-flto` are you able to send more information about your compiler/linker flags?
- When using link-time-optimization, I usually recommend to use in on both the compiler as well as the linker flags and also combine it with `-ffunction-sections` and `-fdata-sections`, as these prepare the sections for LTO better.
- The actual internal compiler error listed in your bug report is from line 51 in `main.cpp`. I think this might be an Arduino environment's `main()` function. Do you or can you see exactly what's going on at that line?
- Can you isolate this error even further by eliminating the use of serial I/O? Maybe have some dependent `if` in the program that only goes on if the `sum` is 6 or similar...

**Comment by ckormanyos** [comment]
>  actual internal compiler error listed in your bug report is from line 51 in `main.cpp`

Also, ... if you are truly getting an internal compiler error, then that's the error right there, the linker is doomed to fail because `main.cpp` is not beoing translated to object code.

If this is the case, then the question is... Why? Why the internal compiler error? You should see if there is or is not an actual error of the kind listed in your original report.

**Comment by asesidaa** [comment]
> Hi @asesidaa I was not at the first pass able to reproduce this error nor any similar error behavior.
> 
> I ran a whole bunch of tests using my own bare-metal (non-Arduino) environment with Zak's new compiler and also with the `avr-libstdcpp` repo. I used numerous STL headers such as `<array>`, `<algorithm>´, `` and more.
> 
> > wonder is this caused by this lib or is this a regression bug in GCC or maybe I am doing something wrong?
> 
> This is exactly what I was wondering. As a next step we should find out if there is something conflicting the new compiler in your environment.
> 
> * I noticed you seem to be using link-time-optimization (probably via `-flto` are you able to send more information about your compiler/linker flags?
> * When using link-time-optimization, I usually recommend to use in on both the compiler as well as the linker flags and also combine it with `-ffunction-sections` and `-fdata-sections`, as these prepare the sections for LTO better.
> * The actual internal compiler error listed in your bug report is from line 51 in `main.cpp`. I think this might be an Arduino environment's `main()` function. Do you or can you see exactly what's going on at that line?
> * Can you isolate this error even further by eliminating the use of serial I/O? Maybe have some dependent `if` in the program that only goes on if the `sum` is 6 or similar...

I am using arduino environment, so the reported error line is from Arduino's framework entry https://github.com/arduino/ArduinoCore-avr/blob/master/cores/arduino/main.cpp#L51

What I notice is that this problem seems to be very specific to Arduino framework's serial I/O and optimization and `accumulate`. Using `__attribute__((optimize("Ox"))) ` to control the optimization level will give different result. When optimization level is `O0` or `O1`, the code compiles, but using `-O2`/`-Os`/`-O3` will all result in error. However, I also tried some different functions in `<algorithm>`, and functions like `binary_search` will not trigger the error.
```C++
#include <Arduino.h>
#include <array>
#include <numeric>

std::array<int, 3> array {1,2,3};

void setup() {
}

// __attribute__((optimize("O1"))) Disable optimization for this function can compile 
__attribute__((optimize("Os"))) // Error
void loop() {
    auto sum = std::accumulate(array.cbegin(), array.cend(), 0); // Error
    // auto sum = std::binary_search(array.cbegin(), array.cend(), 0); This can compile
    Serial.println(sum);
    delay(1000);
}
```

Also, when using other functions to replace `Serial.println`, the code can also compile. For example, if I use another function like `pinMode` to replace, the code also scompiles... But if I change the function call to for example a call to SoftwareSerial's `println` function,  the error will show up again.
```C++
#include <Arduino.h>
#include <array>
#include <numeric>

std::array<int, 3> array {1,2,3};

void setup() {
}

void loop() {
    auto sum = std::accumulate(array.cbegin(), array.cend(), 0);
    pinMode(sum, INPUT); // Compiles
    delay(1000);
}
```

```C++
#include <Arduino.h>
#include <array>
#include <numeric>
#include "SoftwareSerial.h"

std::array<int, 3> array {1,2,3};
SoftwareSerial serial = SoftwareSerial(10, 11);

void setup() {
}

void loop() {
    auto sum = std::accumulate(array.cbegin(), array.cend(), 0);
    serial.println(sum); // Error
    delay(1000);
}
```

**Comment by ckormanyos** [comment]
> my guess is that some optimization is breaking this particular combination of function calls

That seems likely. I scanned the Internet and found the following:

I think somebody else found this [here](https://www.mail-archive.com/gcc-bugs@gcc.gnu.org/mail3.html) and also in more detail and in particular with optimization level 1 or higher, as reported [here](https://www.mail-archive.com/gcc-bugs@gcc.gnu.org/msg738274.html).

When I am confronted with issues such as this, and if I really want to use the compiler, then I usually just figure out the signature of `add_clobbers` and make a local patch for it. Otherwise, the avr-gcc port is really actively supported so patch might be forthcoming (although I'm not sure).

**Comment by ckormanyos** [comment]
Other things to try, ... compile with exceptions and RTTI off. Rattle the cage by making the array and the call to accumulate to be `constexpr`. That sheds absolutely no light on the issue at hand but might be partially insightful. Or, as mentioned above, patch the offending code if this can be done.

**Comment by asesidaa** [comment]
I think this is the issue, so this is actually a compiler regression bug, thank you for taking time to investigate. 

I will use 11.1.0 until this issue is resolve in the compiler.

**Comment by ckormanyos** [comment]
Thanks for reporting and investigating @asesidaa
