### ISSUE TITLE
Maybe include some/most of `std::chrono::high_resolution_clock`

### ISSUE THREAD

**Issue by ckormanyos** [modm-io/avr-libstdcpp#9]
Nice work on this port. I tried it on the AVR target(s) [ckormanyos/real-time-cpp](https://github.com/ckormanyos/real-time-cpp) and it worked essentially out-of-the-box.

I'd like to find in your port an almost-complete implementation of `std::chrono::high_resolution_clock`. You can implement/define everything in that template class _except_ the actual hardware-specific implementation of the subroutine `now()`. You can see a sample below...

I usually put this in as a skeleton in my self-written implementations of `<chrono>`, whenever I have made these. After implementing `std::chrono::high_resolution_clock`, I usually alias `steady_clock`to be the same. In this particular design paradigm, then, the developer has to actually implement `std::shrono::high_resolution_clock::now()`.

If you're interested, ... you might try something like this... in `namespace` `std` in your `<chrono>` (for C++11 and higher), near the bottom of the file.

```C
  namespace chrono
  {
    class high_resolution_clock
    {
    public:
      // defines the accuracy of the (hardware) high resolution clock
      typedef chrono::microseconds duration;

      typedef duration::rep rep;
      typedef duration::period period;
      typedef chrono::time_point<high_resolution_clock, duration> time_point;

      static std::time_t to_time_t(const time_point& t)
      {
        return std::time_t(duration_cast<chrono::seconds>(t.time_since_epoch()).count());
      }

      static time_point from_time_t(std::time_t t)
      {
        typedef chrono::time_point<high_resolution_clock, seconds> _from;
        return time_point_cast<high_resolution_clock::duration>(_from(chrono::seconds(t)));
      }

      // performance counter is steady, a subsequent call to std::chrono::high_resolution_clock::now()
      // returns always a later timer than a previous call
      static constexpr bool is_steady = true;

      // !!! PLATFORM AND OS SPECIFIC IMPLEMENTATION !!!
      static time_point now() noexcept;
    };

    // use high_resolution_clock as steady_clock
    using steady_clock = high_resolution_clock;
  }
```

**Comment by salkinium** [comment]
cc @chris-durand is the expert here.
I would probably also include the `system_clock` interface here.

modm itself uses its [own non-steady interface](https://github.com/modm-io/modm/blob/develop/src/modm/architecture/interface/clock.hpp) and custom implementation, because:
1. The accuracy of the clock depends on the underlying timer, which depends on the clock system. It didn't make sense to have a clock with more than 49 days of uptime, when you should be using a calendar or at least a RTC at that point, which should have a different interface.
2. Using a 64-bit counter is really expensive on AVRs and prevented [several optimizations on both AVR and Cortex-M](https://twitter.com/modm_embedded/status/1270029826641051649) that made a 32-bit counters much cheaper.
3. The stdlibc++ that comes with arm-none-eabi-gcc provided a default implementation of `now()` that was *really* expensive (pulls in half of Newlib) and doesn't work (I think it calls `time()` or something dumb like that).

So we opted to not use this interface and leave it up to the application to implement it if needed.

**Comment by ckormanyos** [comment]
> So we opted to not use this interface and leave it up to the application to implement it if needed.

I understand that. It is a clean and sensible decision.

For my particular purposes, I opt for 64-bit `<chrono>`, regardless of the underlying microcontroller architecture. Now in practice, the user can either provide 32-bit or 64-bit implementation of the member subroutine `now()`. This philosophy does, however, come with some strings attached. i require 1MHz timer counting up, 32-bit (minimum) or 64-bit (better).

I forked your repo and branched for my own purposes. If you would like to see how I ended up putting in `high_resolution_clock`, then it can be found [here](https://github.com/ckormanyos/avr-libstdcpp/blob/376dcd1db1c8c7b5dbb1215a565972dca3e936b7/include/chrono#L1085).

I won't PR this, as I see you have already reached sensible design solution in your domain.

Again, complements/kudos on your port. It is very nice.

**Comment by ckormanyos** [comment]
Thanks for looking at this.

**Comment by chris-durand** [comment]
@salkinium Couldn't we just include the clock headers here as suggested and just not use them in modm?

**Comment by ckormanyos** [comment]
> ... just include the clock headers here as suggested and just not use them in modm?

If this is still open to debate, ... that was, in fact, the idea.

If you would like to pursue this, I can PR my branch/fork. No real pressure from my side, however, as this detail is trivially east to patch wherever/whenever, etc... So I can go either way.

**Comment by salkinium** [comment]
Yes, of course. I'm not against merging this, just wanted to explain why modm went another way. I'm perfectly happy making this repo more useful!

**Comment by ckormanyos** [comment]
> Yes, of course. I'm not against merging this, just wanted to explain why modm went another way. I'm perfectly happy making this repo more useful!

Thx. I will issue a PR.

Hmmm... Now this makes me long for some CI --- even though testing the whole STL is pretty much unheard of within the tiny scope of this project.

So back to reality... I will set up a PR for the `<chrono>` changes only.
